### ISSUE TITLE
Unable to upload a widelands map

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands_website#85]
If you try to upload a map, it shows "please wait..." but nothing happens.

Here is the traceback Holger send me:

Traceback (most recent call last):

File "/var/www/django_projects/3rdparty/django/core/handlers/base.py", line 92, in get_response
   response = callback(request, *callback_args, **callback_kwargs)

File "/var/www/django_projects/3rdparty/django/contrib/auth/decorators.py", line 78, in __call__
   return self.view_func(request, *args, **kwargs)

File "/var/www/django_projects/widelands/wlmaps/views.py", line 140, in upload
   m.load(StringIO(mfdata))

File "/var/www/django_projects/3rdparty/widelandslib/Map.py", line 101, in load
   self._read_elemental( open_file(basedir + 'elemental','r') )

File "/var/www/django_projects/3rdparty/widelandslib/Map.py", line 177, in _read_elemental
   self._descr = cp.getstring("global", "descr")

File "/var/www/django_projects/3rdparty/widelandslib/IniParser.py", line 26, in getstring
   return self.get(s,opt).strip("'\" _")

File "/usr/lib/python2.5/ConfigParser.py", line 525, in get
   return self._interpolate(section, option, value, d)

File "/usr/lib/python2.5/ConfigParser.py", line 593, in _interpolate
   self._interpolate_some(option, L, rawval, section, vars, 1)

File "/usr/lib/python2.5/ConfigParser.py", line 634, in _interpolate_some
   "'%%' must be followed by '%%' or '(', found: %r" % (rest,))

InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '% Land = 45 % Wasteland = 0 % ID = phm?-??jy-??at-??x?-bn?n "'

<ModPythonRequest
path:/maps/upload/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'comment': [u'']}>,
COOKIES:{'sessionid': 'f21d89a9d6111e5b2db99507291e965a'},
META:{'AUTH_TYPE': None,
'CONTENT_LENGTH': 0L,
'CONTENT_TYPE': None,
'GATEWAY_INTERFACE': 'CGI/1.1',
'HTTP_ACCEPT': 'text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1',
'HTTP_ACCEPT_CHARSET': 'iso-8859-1, utf-8, utf-16, *;q=0.1',
'HTTP_ACCEPT_ENCODING': 'deflate, gzip, x-gzip, identity, *;q=0',
'HTTP_ACCEPT_LANGUAGE': 'de,en;q=0.9',
'HTTP_CONNECTION': 'Keep-Alive, TE',
'HTTP_CONTENT_LENGTH': '44726',
'HTTP_CONTENT_TYPE': 'multipart/form-data; boundary=----------CiJREXKjzX6zhzTG6ekTVJ',
'HTTP_COOKIE': 'sessionid=f21d89a9d6111e5b2db99507291e965a',
'HTTP_COOKIE2': '$Version=1',
'HTTP_EXPECT': '100-continue',
'HTTP_HOST': 'wl.widelands.org',
'HTTP_REFERER': 'http://wl.widelands.org/maps/',
'HTTP_TE': 'deflate, gzip, chunked, identity, trailers',
'HTTP_USER_AGENT': 'Opera/9.80 (X11; Linux i686; U; de) Presto/2.2.15 Version/10.00',
'PATH_INFO': u'/maps/upload/',
'PATH_TRANSLATED': None,
'QUERY_STRING': None,
'REMOTE_ADDR': '77.23.17.255',
'REMOTE_HOST': None,
'REMOTE_IDENT': None,
'REMOTE_USER': None,
'REQUEST_METHOD': 'POST',
'SCRIPT_NAME': '',
'SERVER_NAME': 'wl.widelands.org',
'SERVER_PORT': 80,
'SERVER_PROTOCOL': 'HTTP/1.1',
'SERVER_SOFTWARE': 'mod_python'}>

**Comment by gunchleoc** [comment]
(by sirver)
mmh, since we both can't reproduce this atm, I close it till it resurfaces.

**Comment by gunchleoc** [comment]
(by sirver)
I am optimistic and say "Fix released". We fixed it accidentally ;)

**Comment by gunchleoc** [comment]
(by newsgroup-mail)
I try upload a new map with following steps:
  - click upload button
    => screen will be darker
         => nothing else

I found the reason why I cannot upload, after a discuss with Naesenbaer.

There is a popup window for the name of the map and the note,
but the popup window had wrong coordinate's.

x = 1/2 of screen and y = 1/2 of shown list of maps

for example x = 500 and y = 3000

My workaround:
 - I click the upload button
 - screen will be darker
 - I pull the right slider of the main window to the middle to the screen
   => now I see the popup window
   => I can insert map and info and click send 
   => ready

**Comment by gunchleoc** [comment]
(by sirver)
with which browser can you reproduce this problem?
